from __future__ import annotations

"""
Phase 13: PPO Training — Stage 3: Full NLP Agent
================================================
The agent operates entirely on language-derived features:
  - Observes a 9D intent vector produced by an LLM (phi3 / tinyllama) that
    reads the live conversation and RAG policy context.
  - Generates natural-language agent responses via AgentResponseGenerator.
  - Customer responses are generated by NLGLayer (existing, llama3).
  - Together these form a real two-sided conversation that the PPO policy
    learns to steer toward resolution.

Architecture:
  SupportEnv (NLG enabled)
    → NLPObservationWrapper   ← calls IntentClassifier + AgentResponseGenerator
    → RewardShapedWrapper
    → ActionMaskedEnv         ← Escalate blocked for turn_count < 3
    → Monitor

Observation: 9D (intent, confidence, sentiment, suggested_action,
                  escalation_flag, info_completeness, tier_norm,
                  turn_count_norm, failed_streak_norm)
Network:     [64, 32] — small since features are semantically rich

GPU note: Two LLMs run simultaneously (intent classifier + customer NLG).
  phi3 (3.8B, ~7GB) + llama3 (8B, ~15GB) = ~22GB — may not fit in 17GB VRAM.
  Options:
    1. Use tinyllama for intent: --intent-model tinyllama  (~2GB + 15GB = 17GB)
    2. Use phi3 for both:        --intent-model phi3  + set SUPPORT_SIM_LLM_MODEL=phi3
    3. Use n_envs=1 to reduce peak LLM concurrency

Usage:
  python Simulation_4/scripts/phase13_train.py [options]
  python Simulation_4/scripts/phase13_train.py --intent-model tinyllama --n-envs 1
"""

import argparse
import json
import time
import sys
from pathlib import Path
from typing import Any

import torch
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.monitor import Monitor

repo_root = Path(__file__).resolve().parents[2]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from Simulation_4.env.agent_response_generator import AgentResponseGenerator
from Simulation_4.env.support_env import SupportEnv
from Simulation_4.training.action_masking import ActionMaskedEnv
from Simulation_4.training.callbacks import BestModelCallback, CurriculumCallback, TrainingMetricsCallback
from Simulation_4.training.curriculum import CurriculumScheduler
from Simulation_4.training.nlp_observation import NLPObservationWrapper
from Simulation_4.training.reward_shaping import RewardShapedWrapper, RewardShaper


# Smaller network — the 9D observation is already semantically compressed.
NLP_PPO_CONFIG: dict[str, Any] = {
    "policy": "MlpPolicy",
    "policy_kwargs": {
        "net_arch": [64, 32],
        "activation_fn": torch.nn.Tanh,
    },
    "n_steps": 2048,
    "batch_size": 64,          # smaller batch: fewer envs, richer per-step info
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.2,
    "ent_coef": 0.02,          # slightly higher entropy for exploration with LLM noise
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "learning_rate": 1e-4,     # lower LR: LLM features have some variance
    "verbose": 1,
}


def make_nlp_env(
    artifacts_root: str,
    reward_shaper: RewardShaper,
    subflow_filter: list[str] | None,
    intent_model: str,
    agent_model: str,
):
    def _init():
        env = SupportEnv(
            artifacts_root=artifacts_root,
            nlg_enabled=True,          # customer NLG via Ollama/llama3
            subflow_filter=subflow_filter,
        )
        arg = AgentResponseGenerator(model=agent_model)
        env = NLPObservationWrapper(
            env,
            intent_model=intent_model,
            agent_response_generator=arg,
        )
        env = RewardShapedWrapper(env, reward_shaper)
        env = ActionMaskedEnv(env)
        env = Monitor(env)
        return env
    return _init


def train_nlp_ppo(
    artifacts_root: str,
    timesteps: int = 500_000,
    use_curriculum: bool = True,
    use_reward_shaping: bool = True,
    output_subdir: str = "phase13",
    n_envs: int = 2,
    seed: int = 42,
    intent_model: str = "phi3",
    agent_model: str | None = None,
) -> dict[str, Any]:
    if agent_model is None:
        import os
        agent_model = os.getenv("SUPPORT_SIM_LLM_MODEL", "llama3")

    artifacts_root_path = Path(artifacts_root)
    phase_root = artifacts_root_path / output_subdir
    save_dir = phase_root / "models"
    log_dir = phase_root / "tensorboard"
    save_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)

    reward_shaper = RewardShaper(enabled=bool(use_reward_shaping), strict_potential=True)
    curriculum = CurriculumScheduler(str(artifacts_root_path)) if use_curriculum else None
    initial_filter = curriculum.get_subflow_filter(0) if curriculum is not None else None

    train_env = make_vec_env(
        make_nlp_env(
            str(artifacts_root_path),
            reward_shaper,
            initial_filter,
            intent_model=intent_model,
            agent_model=agent_model,
        ),
        n_envs=n_envs,
        seed=seed,
    )

    eval_env = make_nlp_env(
        str(artifacts_root_path),
        RewardShaper(enabled=False),
        subflow_filter=None,
        intent_model=intent_model,
        agent_model=agent_model,
    )()

    model = PPO(
        policy=NLP_PPO_CONFIG["policy"],
        env=train_env,
        policy_kwargs=NLP_PPO_CONFIG["policy_kwargs"],
        n_steps=NLP_PPO_CONFIG["n_steps"],
        batch_size=NLP_PPO_CONFIG["batch_size"],
        n_epochs=NLP_PPO_CONFIG["n_epochs"],
        gamma=NLP_PPO_CONFIG["gamma"],
        gae_lambda=NLP_PPO_CONFIG["gae_lambda"],
        clip_range=NLP_PPO_CONFIG["clip_range"],
        ent_coef=NLP_PPO_CONFIG["ent_coef"],
        vf_coef=NLP_PPO_CONFIG["vf_coef"],
        max_grad_norm=NLP_PPO_CONFIG["max_grad_norm"],
        learning_rate=NLP_PPO_CONFIG["learning_rate"],
        tensorboard_log=str(log_dir),
        verbose=NLP_PPO_CONFIG["verbose"],
        seed=seed,
    )

    metrics_callback = TrainingMetricsCallback(eval_freq=5000, verbose=1)
    best_model_callback = BestModelCallback(
        save_path=str(save_dir),
        eval_env=eval_env,
        eval_freq=10000,
        n_eval_episodes=100,    # fewer eval episodes: LLM calls are expensive
        baseline_reward=0.5,   # lower bar initially — NLP obs is harder
        verbose=1,
    )
    callbacks = [metrics_callback, best_model_callback]

    if curriculum is not None:
        callbacks.append(CurriculumCallback(curriculum, train_env, verbose=1))

    start = time.time()
    model.learn(total_timesteps=int(timesteps), callback=callbacks, progress_bar=True)
    elapsed = float(time.time() - start)

    model.save(str(save_dir / "final_model"))

    training_log = {
        "metrics_history": metrics_callback.history,
        "eval_history": best_model_callback.eval_history,
    }
    (phase_root / "training_log.json").write_text(
        json.dumps(training_log, indent=2), encoding="utf-8"
    )

    summary = {
        "stage": "Phase 13 — Full NLP Agent",
        "total_timesteps": int(timesteps),
        "training_time_seconds": elapsed,
        "curriculum_enabled": bool(use_curriculum),
        "reward_shaping_enabled": bool(use_reward_shaping),
        "nlg_enabled": True,
        "intent_model": intent_model,
        "agent_model": agent_model,
        "observation": "9D NLP intent vector",
        "network": "[64, 32]",
        "n_envs": int(n_envs),
        "seed": int(seed),
        "best_eval_reward": float(best_model_callback.best_mean_reward),
        "baseline_beaten": bool(best_model_callback.baseline_beaten),
        "final_resolution_rate": (
            float(metrics_callback.history[-1]["resolution_rate"]) if metrics_callback.history else 0.0
        ),
    }
    (phase_root / "training_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    train_env.close()
    eval_env.close()
    return summary


def train(args: argparse.Namespace) -> dict:
    artifacts_root = repo_root / "Simulation_4" / "artifacts"

    print("=" * 65)
    print("  PHASE 13: PPO TRAINING — FULL NLP AGENT")
    print("=" * 65)
    print(f"  Timesteps:      {args.timesteps:,}")
    print(f"  Curriculum:     {'enabled' if not args.no_curriculum else 'disabled'}")
    print(f"  Reward shaping: {'enabled' if not args.no_shaping else 'disabled'}")
    print(f"  Intent model:   {args.intent_model}")
    print(f"  Agent model:    {args.agent_model or 'llama3 (default)'}")
    print(f"  Parallel envs:  {args.n_envs}")
    print("  Observation:    9D NLP intent vector")
    print("  Network:        [64, 32] Tanh MLP")
    print("  Escalation cost: Free=6.0, Pro=3.0, Business=0.5, Enterprise=0.0")
    print("  Action mask:    Escalate blocked for turn_count < 3")
    print("=" * 65)
    print()
    print("NOTE: Two LLMs run concurrently (intent classifier + customer NLG).")
    print(f"  Intent: {args.intent_model} | Customer: {args.agent_model or 'llama3'}")
    print("  If VRAM is limited, use --intent-model tinyllama --n-envs 1")
    print()

    summary = train_nlp_ppo(
        artifacts_root=str(artifacts_root),
        timesteps=int(args.timesteps),
        use_curriculum=not bool(args.no_curriculum),
        use_reward_shaping=not bool(args.no_shaping),
        output_subdir="phase13",
        n_envs=int(args.n_envs),
        seed=42,
        intent_model=args.intent_model,
        agent_model=args.agent_model,
    )

    print("\nTraining summary:")
    print(json.dumps(summary, indent=2))
    print("\nArtifacts saved to: Multi-Turn RL/Simulation_4/artifacts/phase13/")
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Phase 13 PPO training — full NLP agent")
    parser.add_argument("--timesteps", type=int, default=500_000)
    parser.add_argument("--no-curriculum", action="store_true")
    parser.add_argument("--no-shaping", action="store_true")
    parser.add_argument(
        "--intent-model", type=str, default="phi3",
        help="Ollama model for intent classification (phi3, tinyllama, llama3)"
    )
    parser.add_argument(
        "--agent-model", type=str, default=None,
        help="Ollama model for agent response generation (defaults to SUPPORT_SIM_LLM_MODEL or llama3)"
    )
    parser.add_argument(
        "--n-envs", type=int, default=2,
        help="Parallel training environments (reduce if VRAM is limited)"
    )
    train(parser.parse_args())
