from __future__ import annotations

"""
Phase 12: PPO Training — Stage 2: Semantic Text Observations
=============================================================
Builds on Stage 1 (phase11) but uses text-derived observations instead of the
9D simulator state. The text_observation.py wrapper now uses
sentence-transformers/all-MiniLM-L6-v2 for dense 384D semantic embeddings
(vs. the original 512D random HashingVectorizer hashes).

Two observable state features (tier_norm, turn_count_norm) are appended,
giving a 386D observation that contains:
  - Semantic meaning of the conversation
  - Who the customer is (tier)
  - How far through the conversation we are

Agent response text is generated by the AgentResponseGenerator (Stage 3 file,
but usable standalone) if available; otherwise falls back to canonical phrases.

Usage:
  python Simulation_4/scripts/phase12_train.py [--timesteps N] [--no-curriculum] [--no-shaping]
"""

import argparse
import json
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parents[2]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from Simulation_4.training.train_ppo import train_ppo


def train(args: argparse.Namespace) -> dict:
    artifacts_root = Path("Simulation_4/artifacts")
    phase_root = artifacts_root / "phase12"
    phase_root.mkdir(parents=True, exist_ok=True)

    print("=" * 65)
    print("  PHASE 12: PPO TRAINING — STAGE 2: SEMANTIC EMBEDDINGS")
    print("=" * 65)
    print(f"  Timesteps:       {args.timesteps:,}")
    print(f"  Curriculum:      {'enabled' if not args.no_curriculum else 'disabled'}")
    print(f"  Reward shaping:  {'enabled' if not args.no_shaping else 'disabled'}")
    print("  Observation:     386D (384D sentence-transformer + tier + turn)")
    print("  NLG:             enabled — real language conversation")
    print("  Escalation cost: Free=6.0, Pro=3.0, Business=0.5, Enterprise=0.0")
    print("  Action mask:     Escalate blocked for turn_count < 3")
    print("  Parallel envs:   4")
    print("=" * 65)

    summary = train_ppo(
        artifacts_root=str(artifacts_root),
        timesteps=int(args.timesteps),
        use_curriculum=not bool(args.no_curriculum),
        use_reward_shaping=not bool(args.no_shaping),
        output_subdir="phase12",
        n_envs=4,
        seed=42,
        nlg_enabled=True,
        text_only_observation=True,   # uses updated text_observation.py (sentence-transformers)
        text_observation_dim=386,     # all-MiniLM-L6-v2 (384) + tier_norm + turn_count_norm
    )

    print("\nTraining summary:")
    print(json.dumps(summary, indent=2))
    print("\nArtifacts:")
    print("  - Simulation_4/artifacts/phase12/models/best_model.zip")
    print("  - Simulation_4/artifacts/phase12/models/final_model.zip")
    print("  - Simulation_4/artifacts/phase12/tensorboard/")
    print("  - Simulation_4/artifacts/phase12/training_log.json")
    print("  - Simulation_4/artifacts/phase12/training_summary.json")
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Phase 12 PPO training — semantic text observations")
    parser.add_argument("--timesteps", type=int, default=750_000,
                        help="Total training timesteps (default: 750k for text-based obs)")
    parser.add_argument("--no-curriculum", action="store_true", help="Disable curriculum learning")
    parser.add_argument("--no-shaping", action="store_true", help="Disable reward shaping")
    train(parser.parse_args())
